version: "3"
services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "4008:4008"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=checker
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
